<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="UnityEngine.Modules" Version="2021.3.15" IncludeAssets="compile" />
    </ItemGroup>
    
    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>..\libdinocop\Assembly-CSharp.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
